export const FORM_CONFIG = 'forms:Form Config';
export const SUBFIELDS = 'forms:Subfield';
export const MESSAGE = 'forms:Message';
export const ERROR_ADDED = 'forms:Error Added';
export const FETCH_LINK = 'forms:Fetch Link';
export const URL_RETRIEVED = 'forms:URL Retrieved';
export const FIELD_VALUE_CHANGE = 'forms:Field Value Changed';
export const FIELD_VALUES_REMOVED = 'forms:Field Value Removed';
export const AVAILABLE_FIELDS_CHANGED = 'forms:Available Fields Changed';
