'use strict';

module.exports = [
	"United States",
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Ashmore and Cartier Islands",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Baker Island",
	"Bangladesh",
	"Barbados",
	"Bassas Da India",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory",
	"British Virgin Islands",
	"Brunei",
	"Bulgaria",
	"Burkina Faso",
	"Burma",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Canal Zone",
	"Canton and Enderbury",
	"Cape Verde",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Clipperton Island",
	"Cocos (Keeling) Islands",
	"Colombia",
	"Comoros",
	"Congo",
	"Congo, Demo Republic of the",
	"Cook Islands",
	"Coral Sea Islands",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Cyprus",
	"Czech Republic",
	"Czechoslovakia",
	"Côte d'Ivoire",
	"Democratic Repub. of Viet-Nam",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Europa Island",
	"Falkland Islands",
	"Faroe Islands",
	"Federated States of Micronesia",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Sthrn &amp; Antarctic Lands",
	"French Terr of Afars and Issas",
	"Gabon",
	"Gambia",
	"Gaza Strip",
	"Georgia",
	"German Democratic Republic",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Gilbert Islands",
	"Gilbert and Ellice Islands",
	"Glorioso Islands",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island &amp; McDonald Island",
	"Honduras",
	"Hong Kong",
	"Howland Island",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Iraq-Saudi Arabia Neutral Zone",
	"Ireland",
	"Isle Of Man",
	"Israel",
	"Israel-Jordan Demil. Zone",
	"Israel-Syria Demil. Zone",
	"Italy",
	"Jamaica",
	"Jan Mayen",
	"Japan",
	"Jarvis Island",
	"Jersey",
	"Johnston Atoll",
	"Jordan",
	"Juan De Nova Island",
	"Kazakhstan",
	"Kenya",
	"Kingman Reef",
	"Kiribati",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macau",
	"Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Midway Islands",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Namibia",
	"Nauru",
	"Navassa Island",
	"Nepal",
	"Netherlands",
	"Netherlands Antilles",
	"Neutral Zone",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"North Korea",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palmyra Atoll",
	"Panama",
	"Papua New Guinea",
	"Paracel Islands",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairn Islands",
	"Poland",
	"Portugal",
	"Portuguese Timor",
	"Puerto Rico",
	"Qatar",
	"Republic Of Viet-Nam",
	"Romania",
	"Russia",
	"Rwanda",
	"Réunion",
	"S. Georgia &amp;S. Sandwich Islands",
	"Saint Barthélemy",
	"Saint Helena",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin",
	"Saint Pierre and Miquelon",
	"Saint Vincent &amp; the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Sikkim",
	"Singapore",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Korea",
	"South Sudan",
	"Southern Rhodesia",
	"Southern Ryukyu Islands",
	"Spain",
	"Spanish North Africa",
	"Spanish Sahara",
	"Spratly Islands",
	"Sri Lanka",
	"Stateless",
	"Sudan",
	"Suriname",
	"Svalbard",
	"Svalbard and Jan Mayen",
	"Swan Islands",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tromelin Island",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"US Misc. Pacific Islands",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vatican City",
	"Venezuela",
	"Vietnam",
	"Virgin Islands",
	"Wake Atoll",
	"Wallis and Futuna",
	"West Bank",
	"Western Sahara",
	"Yemen",
	"Yemen (Aden)",
	"Yemen (Sanaa)",
	"Yugoslavia",
	"Zambia",
	"Zimbabwe"
];
