name: Release

on:
  repository_dispatch:
    types: [release-next]

env:
  CI: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ACTIONS_REPO_ACCESS }}

      - name: clone
        uses: actions/checkout@v2

      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: configure env
        env:
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set loglevel error
          npm config set progress false
          npm config set '@nti:registry' "$NPM_REGISTRY"
          npm config set "${NPM_REGISTRY/https:/}/:_authToken" "$NPM_TOKEN"
          git config user.email support@nextthought.com
          git config user.name nti-jarvis

      - name: Generate release build
        run: npx @nti/release
